"""Partial check on the untestable half of S11.

S11 has two halves. The first, that the owner is credited for the governance
design, is checked by T6 and is fully testable: the line is either present or it
is not.

The second half is that nothing claims or describes who wrote the code. That is
an absence, and an absence cannot be proved by searching, because it would
require a list of every way the thing could be said.

This test therefore does something narrower and says so plainly: it looks for
the phrasings such a claim would most likely take. It catches likely forms only.
**Passing it does not prove the absence.** The reading recorded in
governance/safeguards.md is what covers the rest.
"""

import re

from conftest import REPO_ROOT

# Project prose only. Data files carry text written by the agencies, in which
# these phrases describe their systems rather than this project's code.
SCOPE = ["README.md", "docs/index.html", "docs/gaps.html", "docs/obligations.html",
         "docs/assets/figures.js", "docs/assets/register.js", "docs/assets/views.js"]

LIKELY_CLAIM_FORMS = [
    r"\bI wrote\b", r"\bI built\b", r"\bI coded\b", r"\bI developed\b", r"\bI programmed\b",
    r"\bwritten by\b", r"\bdeveloped by\b", r"\bbuilt by\b", r"\bcoded by\b",
    r"\bauthored by\b", r"\bprogrammed by\b", r"\bimplemented by\b",
    r"\bcode (?:was )?written\b", r"\bwith the help of\b", r"\bgenerated by\b",
    r"\bassisted by\b", r"\bpair[- ]programmed\b",
]

CATCHES_LIKELY_FORMS_ONLY = True


def test_no_likely_claim_about_who_wrote_the_code():
    pattern = re.compile("|".join(LIKELY_CLAIM_FORMS), re.I)
    found = []
    for rel in SCOPE:
        path = REPO_ROOT / rel
        if not path.exists():
            continue
        for m in pattern.finditer(path.read_text()):
            line = path.read_text()[:m.start()].count("\n") + 1
            found.append(f"{rel}:{line} '{m.group(0)}'")
    assert not found, (
        "phrasing that may claim or describe authorship of the code:\n" + "\n".join(found) +
        "\n\nThis test catches likely forms only and does not prove the absence."
    )
